---
# Configuration specific to NAS node (pi-cm5-4)
# This node requires M.2 SATA controller support via PCIe

# Pi CM5 configuration for NAS node - storage node requiring M.2 controller
# PCIe enabled for M.2 SATA/NVMe controller support
pi_cm5_config_pcie_enabled: true  # Required for M.2 SATA controller support

# PCIe generation speed for NAS node
# 3 = PCIe Gen3 for maximum NVMe performance (~2x faster than Gen2)
# Note: Gen3 not officially certified, may cause stability issues with some drives
pi_cm5_config_pcie_generation: 3

# POE configuration for NAS node
# Enable POE support for Waveshare PoE HAT (G) - not needed for cluster on Turing Pi 2
# Reference: https://www.waveshare.com/wiki/PoE_HAT_(G)#How_to_Install
pi_cm5_config_poe_enabled: true

# MinIO storage configuration for NAS node
# Uses persistent disk identifiers (WWN) to avoid device name changes
# Defines the drives to be prepared and used for MinIO data storage
minio_storage_drives:
  - device: /dev/disk/by-id/wwn-0x5000c5008a1a78df
    label: MINIODRIVE1
    mount_point: /mnt/minio-drive1
    filesystem: xfs
  - device: /dev/disk/by-id/wwn-0x5000c5008a1a7d0f
    label: MINIODRIVE2
    mount_point: /mnt/minio-drive2
    filesystem: xfs

# MinIO data directories - used by ricsanfre.minio role
# These paths will be created on the mounted drives
minio_server_datadirs:
  - /mnt/minio-drive1/data
  - /mnt/minio-drive2/data

# MinIO mount options for /etc/fstab
# noatime = performance optimization for object storage workloads
minio_mount_options: "defaults,noatime"

# MinIO server configuration for ricsanfre.minio role
minio_root_user: "miniosuperuser"
minio_root_password: "{{ vault_minio_root_password | default('changeme123') }}"
minio_server_port: 9000
minio_console_port: 9001

# MinIO buckets for different use cases
minio_buckets:
  - name: longhorn-backups
    policy: private
    # Object locking for backup integrity
    object_locking: true
  - name: cluster-logs
    policy: private
  - name: media-storage
    policy: read-write

# MinIO users for service accounts
minio_users:
  - name: longhorn-backup
    password: "{{ vault_longhorn_backup_password | default('longhorn123') }}"
    buckets_acl:
      - name: longhorn-backups
        policy: read-write
  - name: readonly-user
    password: "{{ vault_readonly_user_password | default('readonly123') }}"
    buckets_acl:
      - name: media-storage
        policy: read-only

# Disable cgroups for NAS
pi_cm5_config_cgroup_enabled: false
