---
# Deploy Node Feature Discovery
- name: Deploy Node Feature Discovery
  import_playbook: ../../../playbooks/deploy-helm-app.yml
  vars:
    app_chart_file: "{{ inventory_dir }}/apps/node-feature-discovery/Chart.yml"
    app_values_file: "{{ inventory_dir }}/apps/node-feature-discovery/values.yml"
