---
- name: Deploy Homepage Dashboard
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Apply Homepage manifests
      ansible.builtin.command:
        cmd: kubectl apply -f {{ playbook_dir }}/manifests.yml
      changed_when: true

    - name: Wait for Homepage deployment to be ready
      ansible.builtin.command:
        cmd: kubectl rollout status deployment/homepage -n homepage --timeout=120s
      changed_when: false
