---
# Homepage Dashboard - Dedicated Namespace
# Isolated from applications namespace due to elevated ClusterRole permissions
# for Kubernetes API access (watch ingresses, read metrics)
---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: homepage
  labels:
    name: homepage
---
# NetworkPolicy - Allow API access for service discovery
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: homepage-network-policy
  namespace: homepage
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow Traefik ingress controller from kube-system
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 3000
          protocol: TCP
  egress:
    # DNS resolution via CoreDNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
    # Kubernetes API server (traffic DNATs to control plane nodes)
    - to:
        - ipBlock:
            cidr: 10.43.0.0/16
      ports:
        - port: 443
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 192.168.1.0/24
      ports:
        - port: 6443
          protocol: TCP
    # Applications namespace for service discovery
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: applications
      ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
    # Monitoring namespace (kube-prometheus-stack)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
        - port: 9090
          protocol: TCP
    # Longhorn storage metrics
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: longhorn-system
      ports:
        - port: 9500
          protocol: TCP
---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
---
# ClusterRole - Read-only access for service discovery and metrics
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
  # Services for service discovery
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
---
# ConfigMap: kubernetes.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-kubernetes
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
---
# ConfigMap: settings.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  settings.yaml: |
    title: Homelab Dashboard
    headerStyle: boxed
    providers:
      longhorn:
        url: http://longhorn-backend.longhorn-system.svc.cluster.local:9500
      prometheus:
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
    layout:
      Node Storage:
        style: row
        columns: 4
      Media:
        style: row
        columns: 3
      Monitoring:
        style: row
        columns: 3
      Admin:
        style: row
        columns: 2
---
# ConfigMap: widgets.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-widgets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Homelab Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
---
# ConfigMap: services.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-services
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  services.yaml: |
    - Node Storage:
        - beelink:
            icon: mdi-harddisk
            widget:
              type: prometheusmetric
              url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
              metrics:
                - label: Used
                  query: |
                    100 - (node_filesystem_avail_bytes{instance="192.168.1.76:9100",mountpoint="/"} / node_filesystem_size_bytes{instance="192.168.1.76:9100",mountpoint="/"} * 100)
                  format:
                    type: number
                    suffix: "%"
                - label: Free
                  query: node_filesystem_avail_bytes{instance="192.168.1.76:9100",mountpoint="/"}
                  format:
                    type: bytes
        - pi-cm5-1:
            icon: mdi-raspberry-pi
            widget:
              type: prometheusmetric
              url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
              metrics:
                - label: Used
                  query: |
                    100 - (node_filesystem_avail_bytes{instance="192.168.1.23:9100",mountpoint="/"} / node_filesystem_size_bytes{instance="192.168.1.23:9100",mountpoint="/"} * 100)
                  format:
                    type: number
                    suffix: "%"
                - label: Free
                  query: node_filesystem_avail_bytes{instance="192.168.1.23:9100",mountpoint="/"}
                  format:
                    type: bytes
        - pi-cm5-2:
            icon: mdi-raspberry-pi
            widget:
              type: prometheusmetric
              url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
              metrics:
                - label: Used
                  query: |
                    100 - (node_filesystem_avail_bytes{instance="192.168.1.19:9100",mountpoint="/"} / node_filesystem_size_bytes{instance="192.168.1.19:9100",mountpoint="/"} * 100)
                  format:
                    type: number
                    suffix: "%"
                - label: Free
                  query: node_filesystem_avail_bytes{instance="192.168.1.19:9100",mountpoint="/"}
                  format:
                    type: bytes
        - pi-cm5-3:
            icon: mdi-raspberry-pi
            widget:
              type: prometheusmetric
              url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
              metrics:
                - label: Used
                  query: |
                    100 - (node_filesystem_avail_bytes{instance="192.168.1.13:9100",mountpoint="/"} / node_filesystem_size_bytes{instance="192.168.1.13:9100",mountpoint="/"} * 100)
                  format:
                    type: number
                    suffix: "%"
                - label: Free
                  query: node_filesystem_avail_bytes{instance="192.168.1.13:9100",mountpoint="/"}
                  format:
                    type: bytes
---
# ConfigMap: bookmarks.yaml (empty)
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-bookmarks
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: ""
---
# ConfigMap: docker.yaml (empty - not using Docker integration)
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-docker
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  docker.yaml: ""
---
# ConfigMap: custom.css (empty - required by Homepage)
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-custom-css
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  custom.css: ""
---
# ConfigMap: custom.js (empty - required by Homepage)
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-custom-js
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  custom.js: ""
---
# ConfigMap: proxmox.yaml (empty - required by Homepage)
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-proxmox
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  proxmox.yaml: ""
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      enableServiceLinks: false
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "home.jardoole.xyz"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: kubernetes-config
              mountPath: /app/config/kubernetes.yaml
              subPath: kubernetes.yaml
            - name: settings-config
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
            - name: widgets-config
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
            - name: services-config
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: bookmarks-config
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: docker-config
              mountPath: /app/config/docker.yaml
              subPath: docker.yaml
            - name: custom-css
              mountPath: /app/config/custom.css
              subPath: custom.css
            - name: custom-js
              mountPath: /app/config/custom.js
              subPath: custom.js
            - name: proxmox-config
              mountPath: /app/config/proxmox.yaml
              subPath: proxmox.yaml
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: kubernetes-config
          configMap:
            name: homepage-kubernetes
        - name: settings-config
          configMap:
            name: homepage-settings
        - name: widgets-config
          configMap:
            name: homepage-widgets
        - name: services-config
          configMap:
            name: homepage-services
        - name: bookmarks-config
          configMap:
            name: homepage-bookmarks
        - name: docker-config
          configMap:
            name: homepage-docker
        - name: custom-css
          configMap:
            name: homepage-custom-css
        - name: custom-js
          configMap:
            name: homepage-custom-js
        - name: proxmox-config
          configMap:
            name: homepage-proxmox
        - name: logs
          emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: homepage
---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Homepage"
    gethomepage.dev/description: "Application Dashboard"
    gethomepage.dev/group: "Admin"
    gethomepage.dev/icon: "homepage.png"
spec:
  ingressClassName: traefik
  rules:
    - host: home.jardoole.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  name: http
  tls:
    - secretName: homepage-tls
      hosts:
        - home.jardoole.xyz
