---
# Kubernetes Dashboard deployment playbook
- name: Deploy Headlamp Dashboard
  import_playbook: ../../playbooks/deploy-helm-app.yml
  vars:
    app_chart_file: "{{ inventory_dir }}/apps/headlamp/Chart.yml"
    app_values_file: "{{ inventory_dir }}/apps/headlamp/values.yml"
