---
# Phase 3: MinIO Basic Configuration
# Sets up basic MinIO configuration without SSL complexity

- name: Phase 3 - MinIO Basic Configuration
  hosts: nas
  become: true
  gather_facts: true

  tasks:
    - name: Display Phase 3 overview
      ansible.builtin.debug:
        msg: |
          Phase 3: MinIO Basic Configuration
          ==================================
          - Configure MinIO environment file
          - Set up basic ports and directories
          - Fix data directory ownership
          - NO SSL setup (handled in Phase 4)

    - name: Ensure MinIO configuration directory exists
      ansible.builtin.file:
        path: /etc/minio
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Fix MinIO data directory ownership
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: minio
        group: minio
        recurse: true
      loop: "{{ minio_server_datadirs }}"

    - name: Configure MinIO environment file (basic configuration)
      block:
        - name: Include ricsanfre.minio role for basic configuration
          ansible.builtin.include_role:
            name: ricsanfre.minio
            tasks_from: install_server
          vars:
            minio_enable_tls: false
            minio_install_client: false
            minio_server_port: 9000      # HTTP port for basic config
            minio_console_port: 9001     # HTTP console port
      rescue:
        - name: Note that role restart failed - will handle manually
          ansible.builtin.debug:
            msg: "Role restart failed as expected - will handle restart after SSL cleanup"

    - name: Remove SSL directory to force HTTP-only mode (after role runs)
      ansible.builtin.file:
        path: "{{ minio_cert_path }}"
        state: absent

    - name: Fix MinIO configuration to force HTTP-only mode
      ansible.builtin.replace:
        path: /etc/minio/minio.conf
        regexp: '--certs-dir /etc/minio/ssl\s*'
        replace: ''

    - name: Restart MinIO service after HTTP-only cleanup
      ansible.builtin.systemd:
        name: minio
        state: restarted
        daemon_reload: true

    - name: Verify MinIO can access data directories
      ansible.builtin.command:
        cmd: sudo -u minio test -w "{{ item }}"
      loop: "{{ minio_server_datadirs }}"
      changed_when: false

    - name: Display Phase 3 completion
      ansible.builtin.debug:
        msg: |
          Phase 3 Complete: MinIO Basic Configuration
          ===========================================
          ✓ Configuration directory: /etc/minio/
          ✓ Data directories ownership: minio:minio
          ✓ Environment file: /etc/minio/minio.conf
          ✓ Directory permissions: verified

          Configuration ready for SSL integration (Phase 4)

  handlers:
    - name: Restart minio service
      ansible.builtin.systemd:
        name: minio
        state: restarted
        daemon_reload: true
