[servers]
pi-cm5-1
pi-cm5-2
pi-cm5-3

[desktop]
pi-cm5-4 ansible_host=minio.jardoole.xyz

[storage]
beelink ansible_host=192.168.2.5

[wireguard]
beelink

[ingress]
beelink

[pi_cm5:children]
servers
desktop
