---
# Master orchestration playbook for home lab infrastructure
# Executes base configuration in the correct order for full cluster setup

- name: Home Lab Infrastructure Setup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display setup overview
      ansible.builtin.debug:
        msg: |
          Home Lab Infrastructure Setup
          ============================

          Target Infrastructure:
          - K3s Cluster: pi-cm5-1 (control), pi-cm5-2,3 (workers), Beelink (storage worker)
          - NAS: pi-cm5-4 (MinIO S3 backup server)

          Execution Order:
          1. Base Pi CM5 configuration (all Pi nodes)
          2. System upgrades and security updates
          3. Storage configuration (NAS node disk preparation)
          4. Beelink storage (MergerFS + SnapRAID, 4TB usable)
          5. MinIO storage (MergerFS + SnapRAID, 2TB usable)
          6. MinIO S3 backup service installation
          7. Backup automation (restic + SnapRAID sync)
          8. K3s cluster installation
          9. NFS storage provisioner (K8s integration)

          Storage Architecture:
          - Filesystem-based storage with disk redundancy
          - Direct SSH access to media files
          - Incremental backups with restic

# Phase 1: Base Configuration for all Pi CM5 nodes
- name: Phase 1 - Base Pi CM5 Configuration
  import_playbook: playbooks/pi-base-config.yml

# Phase 2: System maintenance - establish clean base before applications
- name: Phase 2a - System Upgrades
  import_playbook: playbooks/upgrade.yml
- name: Phase 2b - Unattended Upgrades Setup
  import_playbook: playbooks/unattended-upgrades.yml

# Phase 3: Storage-specific configuration for NAS node
- name: Phase 3 - Storage Configuration
  import_playbook: playbooks/pi-storage-config.yml

# Phase 4: Beelink Storage - MergerFS + SnapRAID
- name: Phase 4 - Beelink Storage Configuration
  import_playbook: playbooks/beelink/03-storage-reconfigure-mergerfs.yml

# Phase 5: MinIO Storage - MergerFS + SnapRAID
- name: Phase 5 - MinIO Storage Configuration
  import_playbook: playbooks/nas/minio-storage-reconfigure.yml

# Phase 6: MinIO S3 Service Installation
- name: Phase 6 - MinIO S3 Service
  import_playbook: playbooks/minio-complete.yml

# Phase 7: Backup Automation Setup
- name: Phase 7a - Beelink Restic Backup Setup
  import_playbook: playbooks/beelink/04-restic-backup-setup.yml

- name: Phase 7b - Beelink SnapRAID Automation
  import_playbook: playbooks/beelink/05-snapraid-sync-setup.yml

- name: Phase 7c - MinIO SnapRAID Automation
  import_playbook: playbooks/nas/minio-snapraid-sync-setup.yml

# Phase 8: K3s Cluster Installation
- name: Phase 8 - K3s Cluster
  import_playbook: playbooks/k3s/k3s-complete.yml

# Phase 9: NFS Storage Provisioner
- name: Phase 9 - NFS Storage Provisioner
  import_playbook: apps/nfs-storage/app.yml

# Final status summary
- name: Setup Complete
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display completion status
      ansible.builtin.debug:
        msg: |
          Infrastructure Setup Complete!
          =============================

          ✓ Base Pi CM5 configuration applied
          ✓ System updates completed on clean base
          ✓ Unattended upgrades configured
          ✓ Storage configuration applied to NAS nodes
          ✓ Beelink storage: MergerFS + SnapRAID (4TB usable)
          ✓ MinIO storage: MergerFS + SnapRAID (2TB usable)
          ✓ MinIO S3 backup service with SSL certificates
          ✓ Backup automation: restic + SnapRAID sync timers
          ✓ K3s HA cluster deployed (3-node HA)
          ✓ NFS storage provisioner for K8s integration

          Storage Architecture:
          - Beelink: /mnt/storage (2 data + 1 parity = 4TB, NFS exported)
          - MinIO: /mnt/minio-storage (1 data + 1 parity = 2TB)
          - Direct SSH access to all storage
          - Daily restic backups (3 AM) + SnapRAID sync (4-5 AM)
          - 7 daily, 4 weekly, 6 monthly retention

          Service Access:
          - MinIO Console (HTTPS): https://minio.jardoole.xyz/
          - MinIO API (HTTPS): https://minio.jardoole.xyz:9000
          - K3s API: https://pi-cm5-1:6443 (or pi-cm5-2, pi-cm5-3)
          - Beelink storage: ssh beelink "ls /mnt/storage"

          Storage Classes Available:
          - nfs: Default storage class, RWX, NFS-backed persistent storage

          Next Steps:
          1. Test K3s cluster: kubectl get nodes
          2. Verify storage: kubectl get storageclass
          3. Deploy media stack: make app-deploy APP=media-stack
          4. Verify backups: ssh beelink "restic snapshots"

          Note: System reboots handled automatically during upgrade phase.

          Run 'make site-check' to preview changes before execution.
