---
# Jellyfin deployment playbook
- name: Deploy Jellyfin
  import_playbook: ../../playbooks/deploy-helm-app.yml
  vars:
    app_chart_file: "{{ inventory_dir }}/apps/jellyfin/Chart.yml"
    app_values_file: "{{ inventory_dir }}/apps/jellyfin/values.yml"
    prerequisites_playbook: "{{ inventory_dir }}/apps/jellyfin/prerequisites.yml"
