---
# Jellyfin deployment playbook
# Requires both media stack common prerequisites AND GPU hardware setup

- name: Run media stack common prerequisites
  import_playbook: ../media-stack/_common/prerequisites.yml

- name: Deploy Jellyfin
  import_playbook: ../../playbooks/deploy-helm-app.yml
  vars:
    app_chart_file: "{{ inventory_dir }}/apps/jellyfin/Chart.yml"
    app_values_file: "{{ inventory_dir }}/apps/jellyfin/values.yml"
    prerequisites_playbook: "{{ inventory_dir }}/apps/jellyfin/prerequisites.yml"
