---
# ClusterIssuer for Let's Encrypt with Cloudflare DNS-01 Challenge
# This issuer can create certificates for any namespace in the cluster

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
  labels:
    app.kubernetes.io/name: cert-manager-issuer
    app.kubernetes.io/component: certificate-authority
    app.kubernetes.io/part-of: home-lab-infrastructure
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email for Let's Encrypt account registration
    email: "{{ letsencrypt_email }}"

    # Private key for ACME account
    privateKeySecretRef:
      name: letsencrypt-dns01-private-key

    # DNS-01 challenge configuration using Cloudflare
    solvers:
      - dns01:
          cloudflare:
            # Cloudflare API token with DNS:Edit permissions
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
        selector:
          # This solver applies to all domains under jardoole.xyz
          dnsZones:
            - jardoole.xyz