---
# Radarr deployment playbook
- name: Deploy Radarr
  import_playbook: ../../playbooks/deploy-helm-app.yml
  vars:
    app_chart_file: "{{ inventory_dir }}/apps/radarr/Chart.yml"
    app_values_file: "{{ inventory_dir }}/apps/radarr/values.yml"
    prerequisites_playbook: "{{ inventory_dir }}/apps/media-stack/_common/prerequisites.yml"
