---
# Longhorn Post-Installation Configuration
# These tasks run AFTER Helm deployment to configure backup jobs and policies
# Requires: Longhorn CRDs to be installed

- name: Wait for Longhorn CRDs to be available
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: recurringjobs.longhorn.io
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  register: crd_check
  retries: 30
  delay: 10
  until: crd_check.resources | length > 0

- name: Wait for Longhorn manager to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: longhorn-driver-deployer
    namespace: longhorn-system
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 300

- name: Configure Longhorn backup target
  kubernetes.core.k8s:
    definition:
      apiVersion: longhorn.io/v1beta2
      kind: BackupTarget
      metadata:
        name: default
        namespace: longhorn-system
      spec:
        backupTargetURL: "s3://longhorn-backups@eu-west-1/"
        credentialSecret: "minio-secret"
        pollInterval: "300s"
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Get all Longhorn volumes
  kubernetes.core.k8s_info:
    api_version: longhorn.io/v1beta2
    kind: Volume
    namespace: longhorn-system
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  register: longhorn_volumes

- name: Assign backup jobs to all volumes via labels
  kubernetes.core.k8s:
    api_version: longhorn.io/v1beta2
    kind: Volume
    name: "{{ item.metadata.name }}"
    namespace: longhorn-system
    definition:
      metadata:
        labels:
          recurring-job-group.longhorn.io/default: enabled
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  loop: "{{ longhorn_volumes.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"

- name: Create daily backup recurring job
  kubernetes.core.k8s:
    definition:
      apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: daily-backup
        namespace: longhorn-system
      spec:
        cron: "0 2 * * *"
        task: backup
        groups:
          - default
        retain: 7
        concurrency: 2
        labels:
          recurring-job: daily-backup
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Create weekly backup recurring job
  kubernetes.core.k8s:
    definition:
      apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: weekly-backup
        namespace: longhorn-system
      spec:
        cron: "0 3 * * 0"
        task: backup
        groups:
          - default
        retain: 4
        concurrency: 1
        labels:
          recurring-job: weekly-backup
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Create snapshot cleanup recurring job
  kubernetes.core.k8s:
    definition:
      apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: snapshot-cleanup
        namespace: longhorn-system
      spec:
        cron: "0 6 * * *"
        task: snapshot-cleanup
        groups:
          - default
        retain: 1
        concurrency: 3
        labels:
          recurring-job: snapshot-cleanup
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Create weekly system backup recurring job
  kubernetes.core.k8s:
    definition:
      apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: weekly-system-backup
        namespace: longhorn-system
      spec:
        cron: "0 4 * * 0"
        task: system-backup
        retain: 4
        concurrency: 1
        labels:
          recurring-job: weekly-system-backup
        parameters:
          volume-backup-policy: if-not-present
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Display backup configuration summary
  ansible.builtin.debug:
    msg: |
      ╔═══════════════════════════════════════════════════════════╗
      ║ Longhorn Backup Configuration Complete                   ║
      ╠═══════════════════════════════════════════════════════════╣
      ║ Backup Target: s3://longhorn-backups@eu-west-1/          ║
      ║ Credential Secret: minio-secret                           ║
      ║                                                           ║
      ║ Recurring Jobs:                                           ║
      ║   • daily-backup:    2:00 AM daily (retain 7)            ║
      ║   • weekly-backup:   3:00 AM Sunday (retain 4)           ║
      ║   • snapshot-cleanup: 6:00 AM daily (retain 1)           ║
      ║   • weekly-system-backup: 4:00 AM Sunday (retain 4)      ║
      ╚═══════════════════════════════════════════════════════════╝
