---
# Longhorn Prerequisites
# These tasks run on control_plane before Helm deployment
# Note: System packages on all nodes are handled by orchestration playbook

- name: Create longhorn-system namespace
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: longhorn-system
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Restart CoreDNS for fresh DNS resolution
  ansible.builtin.command:
    cmd: kubectl -n kube-system rollout restart deployment coredns
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  changed_when: true

- name: Wait for CoreDNS to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: coredns
    namespace: kube-system
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 120

- name: Create MinIO credentials secret for Longhorn backups
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: minio-secret
        namespace: longhorn-system
      type: Opaque
      stringData:
        AWS_ACCESS_KEY_ID: "{{ vault_longhorn_s3_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ vault_longhorn_s3_secret_key }}"
        AWS_ENDPOINTS: https://minio.jardoole.xyz:9000
        VIRTUAL_HOSTED_STYLE: "false"
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

# NOTE: BackupTarget and RecurringJobs are configured via values.yml
# They will be created automatically by Longhorn after deployment
