---
# Longhorn Prerequisites
# These tasks run on control_plane before Helm deployment
# Note: System packages on all nodes are handled by orchestration playbook

- name: Restart CoreDNS for fresh DNS resolution
  ansible.builtin.command:
    cmd: kubectl -n kube-system rollout restart deployment coredns
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  changed_when: true

- name: Wait for CoreDNS to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: coredns
    namespace: kube-system
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 120
