---
# Prowlarr deployment playbook
- name: Deploy Prowlarr
  import_playbook: ../../playbooks/deploy-helm-app.yml
  vars:
    app_chart_file: "{{ inventory_dir }}/apps/prowlarr/Chart.yml"
    app_values_file: "{{ inventory_dir }}/apps/prowlarr/values.yml"
    prerequisites_playbook: "{{ inventory_dir }}/apps/media-stack/_common/prerequisites.yml"
