---
# qBittorrent deployment playbook
- name: Deploy qBittorrent
  import_playbook: ../../playbooks/deploy-helm-app.yml
  vars:
    app_chart_file: "{{ inventory_dir }}/apps/qbittorrent/Chart.yml"
    app_values_file: "{{ inventory_dir }}/apps/qbittorrent/values.yml"
    prerequisites_playbook: "{{ inventory_dir }}/apps/media-stack/_common/prerequisites.yml"
