---
# Demo App Deployment Playbook
# Demonstrates persistent storage and SSL certificate integration

- name: Deploy Demo App
  import_playbook: ../../playbooks/deploy-helm-app.yml
  vars:
    app_chart_file: "{{ inventory_dir }}/apps/demo-app/Chart.yml"
    app_values_file: "{{ inventory_dir }}/apps/demo-app/values.yml"
