---
# Jellyseerr deployment playbook
- name: Deploy Jellyseerr
  import_playbook: ../../playbooks/deploy-helm-app.yml
  vars:
    app_chart_file: "{{ inventory_dir }}/apps/jellyseerr/Chart.yml"
    app_values_file: "{{ inventory_dir }}/apps/jellyseerr/values.yml"
    prerequisites_playbook: "{{ inventory_dir }}/apps/media-stack/_common/prerequisites.yml"
