---
# Install and configure MinIO S3 storage on NAS node
# Uses ricsanfre.minio role with prepared storage from Phase 4a

- name: Install and configure MinIO S3 storage
  hosts: nas
  become: true
  gather_facts: true

  pre_tasks:
    - name: Create MinIO data directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop: "{{ minio_server_datadirs }}"
      tags:
        - setup

    - name: Verify storage preparation is complete
      ansible.builtin.stat:
        path: "{{ item }}"
      register: storage_check
      failed_when: not storage_check.stat.exists and not ansible_check_mode
      loop: "{{ minio_server_datadirs }}"
      tags:
        - verification

    - name: Display pre-installation status
      ansible.builtin.debug:
        msg: |
          MinIO installation starting:
          - Storage directories: {{ minio_server_datadirs | length }} verified
          - Root user: {{ minio_root_user }}
          - Server port: {{ minio_server_port }}
          - Console port: {{ minio_console_port }}
          - Buckets to create: {{ minio_buckets | length }}
          - Users to create: {{ minio_users | length }}
      tags:
        - verification

  roles:
    - role: ricsanfre.minio
      tags:
        - minio-install

  post_tasks:
    - name: Wait for MinIO service to be ready
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}:{{ minio_server_port }}/minio/health/live"
        method: GET
        status_code: 200
      retries: 30
      delay: 2
      register: health_check
      until: health_check.status == 200
      tags:
        - verification

    - name: Verify MinIO console is accessible
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}:{{ minio_console_port }}"
        method: GET
        status_code: 200
      retries: 10
      delay: 2
      tags:
        - verification

    - name: Display MinIO setup summary
      ansible.builtin.debug:
        msg: |
          MinIO installation complete!
          ===========================

          Access Information:
          - MinIO Console: http://{{ inventory_hostname }}:{{ minio_console_port }}
          - MinIO API: http://{{ inventory_hostname }}:{{ minio_server_port }}
          - Root Username: {{ minio_root_user }}
          - Root Password: [check vault or defaults]

          Created Buckets:
          {% for bucket in minio_buckets %}
          - {{ bucket.name }} ({{ bucket.policy }}){% if bucket.object_locking | default(false) %} [locked]{% endif %}
          {% endfor %}

          Created Users:
          {% for user in minio_users %}
          - {{ user.name }} (access to: {{ user.buckets_acl | map(attribute='name') | join(', ') }})
          {% endfor %}

          Next Steps:
          1. Access web console to verify setup
          2. Test S3 operations with mc client or boto3
          3. Configure Longhorn backup target
      tags:
        - summary
