---
# Complete MinIO installation with SSL certificates - REDIRECT TO MODULAR VERSION
# This file now redirects to the new modular approach for better maintainability

- name: Redirect to Modular MinIO Installation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display redirect message
      ansible.builtin.debug:
        msg: |
          🔄 MinIO Installation Redirected to Modular Approach
          ===================================================

          This playbook now uses a modular approach for better maintainability.
          The installation has been broken down into independent, testable phases.

          Redirecting to: playbooks/minio/minio-complete.yml

# Import the modular MinIO installation
- name: Run Modular MinIO Installation
  import_playbook: minio/minio-complete.yml
