---
# Configure Raspberry Pi CM5 storage and PCIe settings
# Enables PCIe for NAS nodes, disables for cluster nodes based on group variables

- name: Configure Pi CM5 storage and PCIe settings
  hosts: all
  become: true
  gather_facts: true

  roles:
    - pi_cm5_config

  post_tasks:
    - name: Display configuration summary
      ansible.builtin.debug:
        msg: |
          Pi CM5 configuration applied:
          - Base settings: 64-bit mode, minimal GPU memory, disabled camera/display detection
          - Power optimization: WiFi/Bluetooth/HDMI audio disabled (~200mW savings)
          - PCIe: {{ 'Enabled' if pi_pcie_enabled else 'Disabled' }}
            ({{ 'NAS mode' if pi_pcie_enabled else 'power saving' }})

          Reboot required to apply changes.
      tags:
        - summary
