---
# Media Stack Prerequisites
# Shared storage infrastructure for all media applications
# Creates namespace, PVC, and initializes directory structure

- name: Create media namespace
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: media
        labels:
          name: media
          managed-by: ansible
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Create ProtonVPN Secret for qBittorrent
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: protonvpn-secret
        namespace: media
        labels:
          app: qbittorrent
          managed-by: ansible
      type: Opaque
      stringData:
        openvpn-username: "{{ vault_protonvpn_username }}"
        openvpn-password: "{{ vault_protonvpn_password }}"
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Create qBittorrent Credentials Secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: qbittorrent-secret
        namespace: media
        labels:
          app: qbittorrent
          managed-by: ansible
      type: Opaque
      stringData:
        password: "{{ vault_qbittorrent_password }}"
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Create media-stack-data PersistentVolumeClaim
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: media-stack-data
        namespace: media
        labels:
          app: media-stack
          managed-by: ansible
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: nfs-media
        resources:
          requests:
            storage: 4Ti
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Check if directory initialization has already completed
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    name: media-stack-init-dirs
    namespace: media
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  register: init_job_status

- name: Check if job is already complete
  ansible.builtin.set_fact:
    job_is_complete: "{{ init_job_status.resources | length > 0 and init_job_status.resources[0].status.succeeded | default(0) > 0 }}"

- name: Initialize media stack directory structure
  kubernetes.core.k8s:
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: media-stack-init-dirs
        namespace: media
        labels:
          app: media-stack
          managed-by: ansible
      spec:
        backoffLimit: 3
        template:
          metadata:
            labels:
              app: media-stack-init
          spec:
            restartPolicy: OnFailure
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - beelink
            containers:
              - name: init-directories
                image: busybox:1.36
                command:
                  - sh
                  - -c
                  - |
                    echo "Creating media stack directory structure..."
                    mkdir -p /data/torrents/movies
                    mkdir -p /data/torrents/tv
                    mkdir -p /data/torrents/incomplete
                    mkdir -p /data/media/movies
                    mkdir -p /data/media/tv
                    chmod -R 777 /data
                    echo "Directory structure created:"
                    ls -laR /data
                    echo "Initialization complete!"
                volumeMounts:
                  - name: data
                    mountPath: /data
                resources:
                  requests:
                    cpu: 10m
                    memory: 32Mi
                  limits:
                    cpu: 50m
                    memory: 64Mi
            volumes:
              - name: data
                persistentVolumeClaim:
                  claimName: media-stack-data
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  when: not job_is_complete

- name: Wait for directory initialization job to complete
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    name: media-stack-init-dirs
    namespace: media
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: true
    wait_condition:
      type: Complete
      status: "True"
    wait_timeout: 300
  when: not job_is_complete
